version: '3.8'
services:
  web:
    build: .
    command: gunicorn rankingproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./ranking:/app
      - static_volume:/app/static
    expose:
      - 8000

  nginx:
    image: nginx:1.19
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
