# Generated by Django 4.2.7 on 2024-01-27 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rankingapp', '0003_rankingmodel_buisiness_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingmodel',
            name='created_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
