# Generated by Django 4.2.7 on 2024-01-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankingapp', '0004_rankingmodel_created_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingmodel',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
