# Generated by Django 4.2.7 on 2024-01-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankingapp', '0002_rankingmodel_shop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingmodel',
            name='buisiness_hours',
            field=models.CharField(default='10-22', max_length=100),
            preserve_default=False,
        ),
    ]
