# Generated by Django 4.2.7 on 2024-01-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankingapp', '0005_rankingmodel_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingmodel',
            name='shop_image',
            field=models.ImageField(default='shop.png', upload_to='images/'),
            preserve_default=False,
        ),
    ]
