# Generated by Django 4.2.7 on 2024-02-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankingapp', '0006_rankingmodel_shop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shop_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
